compressionLevel: mixed
defaultSemverRangePrefix: ""
enableGlobalCache: false
yarnPath: .yarn/releases/yarn-4.6.0.cjs
supportedArchitectures:
  cpu:
    - arm64
    - x64
  os:
    - darwin
    - linux
    - win32
